logConfig: {
  logFile: 'appLog.log',
}

dbConfig: {
  dbFile: 'obsidianFile.db'
}

fileSelectConfig: {
  vaultPath: 'C:\Users\rando\Desktop\testEFM',
  ignoreRegexes: [
    '\.obsidian',
    '\.git',
    '\.json',
    '\.html',
    '\.rar',
    '\.zip',
    'EFCore',
    '\.md',
    '\.srt',
    '\.ass',
  ],
  destinationPath: 'C:\Users\rando\Desktop\testDest'
}

fileParseConfig: {
  replaceWikiLink: true,
  replaceAdmontion: true,
  addYamlInfo: true,
}